[2024-03-25T17:12:03.930+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: loan_prediction.run_ML_models manual__2024-03-25T17:11:31.500070+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
[2024-03-25T17:59:59.256+0000] {scheduler_job_runner.py:1755} ERROR - Detected zombie job: {'full_filepath': '/opt/airflow/dags/dag.py', 'processor_subdir': '/opt/airflow/dags', 'msg': "{'DAG Id': 'loan_prediction', 'Task Id': 'run_ML_models', 'Run Id': 'manual__2024-03-25T17:11:31.500070+00:00', 'Hostname': 'e7ab723b212e', 'External Executor Id': '36b6c119-79a3-44d3-b7dd-d3456a0bf485'}", 'simple_task_instance': <airflow.models.taskinstance.SimpleTaskInstance object at 0x734a6a00cc70>, 'is_failure_callback': True} (See https://airflow.apache.org/docs/apache-airflow/stable/core-concepts/tasks.html#zombie-undead-tasks)
